#!/bin/bash

AUTH="authorization: Basic $OBS_AUTH"
BASE_URL="https://api.opensuse.org/source/$OBS_PROJECT/$PACKAGE"

git clone https://aur.archlinux.org/${PACKAGE}.git
chown -R build:build $PACKAGE

# if it's new package can't do verification
if [[ ${new_pkg+x} ]]; then
    exit 0
fi

cd ${PACKAGE}

curl -XGET -H "$AUTH" "$BASE_URL/PKGBUILD" -o PKGBUILD.old
sudo -u build makepkg -p PKGBUILD.old --printsrcinfo | cmp -s .SRCINFO -

# exit code 0 means there's no need to update
if [[ $? -eq 0 ]]; then
	echo "no_changes=1" >> $GITHUB_ENV
fi

