#!/bin/bash

if [[ ${no_changes+x} ]]; then
    exit 0
fi

cd ${PACKAGE}

# TODO: generate constraints programatically
cat > "_constraints" << EOF
<constraints>
</constraints>
EOF

# generate _service file
python ../.github/workflows/mirror/gen-service.py

