name: Build git packages
on:
    schedule:
        - cron: '0 0 * * *'

defaults:
    run:
        shell: bash

jobs:
    main-git:
        env:
            PACKAGE: ${{ matrix.PKGS }}
            OBS_AUTH: ${{ secrets.OBS_AUTH }}
            OBS_PROJECT: ${{ secrets.OBS_PROJECT }}
        runs-on: ubuntu-latest
        container: justkdng/archlinux:latest
        strategy:
            fail-fast: false
            matrix:
                PKGS: [
                        "xorgproto-git",
                        "xorg-server-git",
                        "xf86-video-amdgpu-git"
                      ]
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Prepare environment
              run: .github/workflows/env
            - name: Run prepare()
              run: sudo -u build -EH bash -c .github/workflows/prepare
            - name: Trigger OBS build
              run: .github/workflows/obs_trigger

