#!/bin/bash

_git_pkg()
{
    # PKGBUILD after prepare() has updated pkgver
    rm PKGBUILD
    cp /home/build/PKGBUILD .

    # remove pkgver function
    sed -i '/^pkgver() {$/,/^}$/d' PKGBUILD
}

_gen_constraints()
{
cat > "_constraints" << EOF
<!-- vim: set ft=xml : -->
<constraints>
  <hardware>
    <disk>
      <size unit="G">16</size>
    </disk>
    <memory>
      <size unit="G">16</size>
    </memory>
  </hardware>
</constraints>
EOF
}

_empty_constraints()
{
cat > "_constraints" << EOF
<!-- vim: set ft=xml : -->
<constraints>
</constraints>
EOF
}

mongodb()
{
python ../.github/workflows/mirror/gen-service.py

cat > "_constraints" << EOF
<!-- vim: set ft=xml : -->
<constraints>
  <hardware>
    <memory>
      <size unit="G">12</size>
    </memory>
  </hardware>
</constraints>
EOF
}

python-stdnum()
{
	python ../.github/workflows/mirror/gen-service.py

	_empty_constraints
}

ungoogled-chromium()
{

source PKGBUILD

# Add required dependencies for OBS
newdeps=$(printf "'%s' " "${depends[@]}")
makedeps=$(printf "'%s' " "${makedepends[@]}")

makedeps=$(printf '%s\n' "${makedeps//\'java-runtime-headless\'/}")
makedeps="${makedeps}'jack' 'jre-openjdk-headless' 'wayland-protocols'"

sed -r -i \
    -e '/^depends=/,/[)]$/cdepends=('"${newdeps}"')' \
    -e '/^depends[+]=/d' \
    -e '/^makedepends=/,/[)]$/cmakedepends=('"${makedeps}"')' \
    "PKGBUILD"

python ../.github/workflows/mirror/gen-service.py

_gen_constraints
}

xorgproto-git()
{
_git_pkg

source PKGBUILD

# replace git url
new_url="\${pkgname}.tar"
sed_param=s/_srcurl=.*/_srcurl=\"${new_url}\"/
sed -i "$sed_param" PKGBUILD

# generate _service file
cat > "_service" << EOF
<services>
  <service name="tar_scm">
    <param name="scm">git</param>
    <param name="url">https://gitlab.freedesktop.org/xorg/proto/$_pkgname.git</param>
    <param name="filename">$pkgname</param>
    <param name="version">_none_</param>
  </service>
</services>
EOF

_gen_constraints
}

linux-amd-staging-drm-next-git()
{
_git_pkg

source PKGBUILD

# replace git url
new_url="\${_srcname}.tar"
sed_param=s/_srcurl=.*/_srcurl=\"${new_url}\"/
sed -i "$sed_param" PKGBUILD

# generate _service file
cat > "_service" << EOF
<services>
  <service name="tar_scm">
    <param name="scm">git</param>
    <param name="url">git://people.freedesktop.org/~agd5f/linux</param>
    <param name="revision">amd-staging-drm-next</param>
    <param name="filename">linux-agd5f</param>
    <param name="version">_none_</param>
  </service>
</services>
EOF

_gen_constraints
}

xorg-server-git()
{
_git_pkg

source PKGBUILD

# replace git url
new_url="\${_pkgbase}.tar"
sed_param=s/_srcurl=.*/_srcurl=\"${new_url}\"/
sed -i "$sed_param" PKGBUILD

# generate _service file
cat > "_service" << EOF
<services>
  <service name="tar_scm">
    <param name="scm">git</param>
    <param name="url">https://gitlab.freedesktop.org/xorg/xserver.git</param>
    <param name="filename">$_pkgbase</param>
    <param name="version">_none_</param>
  </service>
</services>
EOF
_gen_constraints
}

xf86-video-amdgpu-git()
{
_git_pkg

source PKGBUILD

# replace git url
new_url="\${pkgname}.tar"
sed_param=s/_srcurl=.*/_srcurl=\"${new_url}\"/
sed -i "$sed_param" PKGBUILD

# generate _service file
cat > "_service" << EOF
<services>
  <service name="tar_scm">
    <param name="scm">git</param>
    <param name="url">https://gitlab.freedesktop.org/xorg/driver/$_pkgname</param>
    <param name="filename">$pkgname</param>
    <param name="version">_none_</param>
  </service>
</services>
EOF

_gen_constraints
}

linux-firmware-git()
{
_git_pkg

source PKGBUILD

# replace git url
new_url="\$pkgbase.tar"
sed_param=s/_srcurl=.*/_srcurl=\"${new_url}\"/
sed -i "$sed_param" PKGBUILD

# generate _service file
cat > "_service" << EOF
<services>
  <service name="tar_scm">
    <param name="scm">git</param>
    <param name="url">https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git</param>
    <param name="filename">$pkgbase</param>
    <param name="revision">main</param>
    <param name="version">_none_</param>
  </service>
</services>
EOF

_gen_constraints
}

linux-kamakiri()
{
source PKGBUILD

new_url="\$pkgbase.tar"
sed_param=s/_srcurl=.*/_srcurl=\"${new_url}\"/
sed -i "$sed_param" PKGBUILD

# generate _service file
cat > "_service" << EOF
<services>
  <service name="tar_scm">
    <param name="scm">git</param>
    <param name="url">https://git.archlinux.org/linux.git</param>
    <param name="filename">$pkgbase</param>
    <param name="revision">$_srctag</param>
    <param name="version">_none_</param>
  </service>
</services>
EOF

_gen_constraints
}

