#!/bin/bash

_git_pkg()
{
    # PKGBUILD after prepare() has updated pkgver
    rm PKGBUILD
    cp /home/build/PKGBUILD .

    # remove pkgver function
    sed -i '/^pkgver() {$/,/^}$/d' PKGBUILD
}

ungoogled-chromium()
{

source PKGBUILD

# Add required dependencies for OBS
newdeps=$(printf "'%s' " "${depends[@]}")
makedeps=$(printf "'%s' " "${makedepends[@]}")

makedeps=$(printf '%s\n' "${makedeps//\'java-runtime-headless\'/}")
makedeps="${makedeps}'jack' 'jre-openjdk-headless'"

sed -r -i \
    -e '/^depends=/,/[)]$/cdepends=('"${newdeps}"')' \
    -e '/^depends[+]=/d' \
    -e '/^makedepends=/,/[)]$/cmakedepends=('"${makedeps}"')' \
    "PKGBUILD"

# Generate _service file
cat > "_service" << EOF
<services>
  <service name="download_url">
    <param name="protocol">https</param>
    <param name="host">commondatastorage.googleapis.com</param>
    <param name="path">/chromium-browser-official/chromium-${_pkgver}.tar.xz</param>
    <param name="filename">chromium-${_pkgver}.tar.xz</param>
  </service>
  <service name="download_url">
    <param name="protocol">https</param>
    <param name="host">github.com</param>
    <param name="path">/foutrelis/chromium-launcher/archive/v6.tar.gz</param>
    <param name="filename">chromium-launcher-6.tar.gz</param>
  </service>
  <service name="download_url">
    <param name="protocol">https</param>
    <param name="host">github.com</param>
    <param name="path">/Eloston/ungoogled-chromium/archive/${_ungoogled_ver}.tar.gz</param>
    <param name="filename">ungoogled-chromium-${_ungoogled_ver}.tar.gz</param>
  </service>
  <service name="obs_scm">
    <param name="scm">git</param>
    <param name="url">git://github.com/jstkdng/aur</param>
    <param name="revision">obs</param>
    <param name="extract">${PACKAGE}/chromium.install</param>
    <param name="extract">${PACKAGE}/chromium-drirc-disable-10bpc-color-configs.conf</param>
    <param name="extract">${PACKAGE}/*.patch</param>
  </service>
</services>
EOF

}

ungoogled-chromium-ozone()
{
    ungoogled-chromium
}

ungoogled-chromium-git()
{
    _git_pkg
    ungoogled-chromium

    # replace ungoogled chromium url
    new_url="\$_pkgname-\$_ungoogled_ver.tar.gz::https:\/\/github.com\/Eloston\/ungoogled-chromium\/archive\/\$_ungoogled_ver.tar.gz"
    sed_param=s/_uc_url=.*/_uc_url=\"${new_url}\"/
    sed -i "$sed_param" PKGBUILD
}

linux-amd-staging-drm-next-git()
{
_git_pkg

source PKGBUILD

# replace git url
new_url="\${_srcname}.tar"
sed_param=s/_srcurl=.*/_srcurl=\"${new_url}\"/
sed -i "$sed_param" PKGBUILD

# generate _service file
cat > "_service" << EOF
<services>
  <service name="obs_scm">
    <param name="scm">git</param>
    <param name="url">git://github.com/jstkdng/aur</param>
    <param name="revision">obs</param>
    <param name="extract">${PACKAGE}/config</param>
    <param name="extract">${PACKAGE}/*.patch</param>
  </service>
  <service name="tar_scm">
    <param name="scm">git</param>
    <param name="url">git://people.freedesktop.org/~agd5f/linux</param>
    <param name="revision">amd-staging-drm-next</param>
    <param name="filename">linux-agd5f</param>
    <param name="version">_none_</param>
  </service>
</services>
EOF
}
