#!/bin/bash

function ungoogled-chromium()
{

BRANCH=master
if [ ! -z "$1" ]; then
    BRANCH=$1
fi

source PKGBUILD

# Add required dependencies for OBS
newdeps=$(printf "'%s' " "${depends[@]}")
makedeps=$(printf "'%s' " "${makedepends[@]}")

makedeps=$(printf '%s\n' "${makedeps//\'java-runtime-headless\'/}")
makedeps="${makedeps}'jack' 'jre-openjdk-headless'"

sed -r -i \
    -e '/^depends=/,/[)]$/cdepends=('"${newdeps}"')' \
    -e '/^depends[+]=/d' \
    -e '/^makedepends=/,/[)]$/cmakedepends=('"${makedeps}"')' \
    "PKGBUILD"

# Generate _service file
cat > "_service" << EOF
<services>
  <service name="download_url">
    <param name="protocol">https</param>
    <param name="host">commondatastorage.googleapis.com</param>
    <param name="path">/chromium-browser-official/chromium-${pkgver}.tar.xz</param>
    <param name="filename">chromium-${pkgver}.tar.xz</param>
  </service>
  <service name="download_url">
    <param name="protocol">https</param>
    <param name="host">github.com</param>
    <param name="path">/foutrelis/chromium-launcher/archive/v6.tar.gz</param>
    <param name="filename">chromium-launcher-6.tar.gz</param>
  </service>
  <service name="download_url">
    <param name="protocol">https</param>
    <param name="host">github.com</param>
    <param name="path">/Eloston/ungoogled-chromium/archive/${_ungoogled_ver}.zip</param>
    <param name="filename">ungoogled-chromium-${_ungoogled_ver}.zip</param>
  </service>
  <service name="tar_scm">
    <param name="scm">git</param>
    <param name="url">git://github.com/jstkdng/ungoogled-chromium-archlinux</param>
    <param name="revision">${BRANCH}</param>
    <param name="extract">chromium.install</param>
    <param name="extract">chromium-drirc-disable-10bpc-color-configs.conf</param>
    <param name="extract">*.patch</param>
  </service>
</services>
EOF

}

function ungoogled-chromium-ozone()
{
    ungoogled-chromium ozone
}
