#!/bin/bash

if [[ ${no_changes+x} ]]; then
    exit 0
fi

cd "$PACKAGE"

declare -a FILES=(PKGBUILD _service _constraints)

AUTH="authorization: Basic $OBS_AUTH"
BASE_URL="https://api.opensuse.org/source/$OBS_PROJECT/$PACKAGE"

source $GITHUB_WORKSPACE/.github/workflows/obs_files

"$PACKAGE"  # generate/modify files for OBS

for FILE in "${FILES[@]}"
do
    URL="$BASE_URL/$FILE?rev=upload"
    curl -XPUT -H 'Content-Type: application/octet-stream' -H "$AUTH" --data-binary "@$FILE" $URL
done

curl -XPOST -H "$AUTH" "$BASE_URL" -F "cmd=commit"
